=== darkone0112/xml/xmlSchema/libros.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="libros">
		<complexType>
			<sequence>
				<element name="libro" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="libro">
		<sequence>
			<element name="titulo" type="string" />
			<element name="autor">
				<simpleType>
					<restriction base="string">
						<enumeration value="quevedo"></enumeration>
						<enumeration value="reverte"></enumeration>
						<enumeration value="cervantez"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="isbn" minOccurs="0" maxOccurs="1" type="string"/>
            <element name="precio" minOccurs="0" type="integer"/>
        </sequence>
	</complexType>
    <element name="precio">
        <simpleType>
            <restriction base="decimal">
				<minInclusive value="0"></minInclusive>
				<maxInclusive value="6"></maxInclusive>
            </restriction>
        </simpleType>
    </element>
</schema>

=== darkone0112/xml/xmlSchema/libros_dtd_int.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:noNamespaceSchemaLocation = "libros.xsd">
	<libro>
		<titulo>�jjjjj</titulo>
	    <autor>kkkk</autor>
	    <isbn>bc-11111</isbn>
		<precio>1.20</precio>
	</libro>
	<libro>
		<titulo>�kkkkkkk</titulo>
	    <autor>jjjjj</autor>
		<autor>mmmmm</autor>
	    <isbn>dd-11111</isbn>
		<precio>1.45</precio>
	</libro>
	<libro>
		<titulo>mmmmmmmmmmmm</titulo>
	    <autor>bbbbbbbbb</autor>
	    <precio>3.44</precio>
	</libro>
	<libro>
		<titulo>���hhhhhh</titulo>
	    <autor>gggggg</autor>
	  	<precio>6</precio>
		<precio>5.6</precio>
		
	</libro>
	<libro>
		<titulo>hhhhhhh</titulo>
	    <autor>ggggggg</autor>
	    <isbn>tt-6666</isbn>
	</libro>	
</libros>
