=== darkone0112/xml/xmlSchema/noticias.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="noticias">
		<complexType>
			<sequence>
				<element name="noticia" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="titulo" type="string" minOccurs="1"/>
						<element name="autor" type="string" minOccurs="1" maxOccurs="2"/>
						<element name="url" minOccurs="1">
							<complexType>
								<attribute name="direccion" type="string" use="required"/>
							</complexType>
						</element>
						<element name="texto" type="string" minOccurs="0" maxOccurs="1"/>
						<element name="foto" type="string" minOccurs="0" maxOccurs="1"/>
					</sequence>
					<attribute name="fecha" type="date" use="required"/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== darkone0112/xml/xmlSchema/noticias.xml
<?xml version="1.0" encoding="UTF-8"?>
<noticias   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"    xsi:noNamespaceSchemaLocation = "noticias.xsd">
	<noticia fecha="2010-11-12">
		<titulo> Nuevo Servidor WEB </titulo>
		<autor> Antonio Barco </autor >
		<url direccion="http://www.abc.es"/>
		<texto> En los últimos días ha visto la luz un nuevo servidor Web en la  Comunidad Valenciana </texto >
		
	</noticia>
	<noticia fecha="2011-01-12">
		<titulo> Premio de Biología </titulo>
		<autor> Pilar Garcia</autor >
		<url direccion="http://www.abc.es"/>
		<texto> Los alumnos del Colegio Europa ganan el premio de Biología de la Comunidad Autónoma de Andalucía </texto >
		<foto>http://www.abc.es/123.jpg</foto>
	</noticia>
</noticias>
