=== darkone0112/xml/xmlSchema/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="videoclub">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="cliente" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="dni">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="nombre"></xs:element>
                    <xs:element name="apellido1"></xs:element>
                    <xs:element name="apellido2"></xs:element>
                    <xs:element name="telefono"></xs:element>
                </xs:sequence>
                <xs:attribute name="id" type="xs:ID" use="required" ></xs:attribute>
            </xs:complexType>
        </xs:element>
        <xs:element name="factura" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="resguardo">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pago">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="efectivo"></xs:enumeration>
                                            <xs:enumeration value="tarjeta"></xs:enumeration>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="importe"></xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="alquileres" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="pelicula">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="titulo"></xs:element>
                                            <xs:element name="genero"></xs:element>
                                            <xs:element name="duracion"></xs:element>
                                            <xs:element name="actor" minOccurs="3" maxOccurs="3">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="nombre"></xs:element>
                                                        <xs:element name="apellidos"></xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="idpelicula" type="xs:ID" use="required"></xs:attribute>
                                        <xs:attribute name="valoracion" use="required">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="1"></xs:minInclusive>
                                                    <xs:maxInclusive value="10"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                            <xs:attribute name="fecha" type="xs:date" use="required"></xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="compras">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="dvd" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="extras">
                                                <xs:complexType></xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="fecha" type="xs:date"></xs:attribute>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="cinta">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="rebobinada">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="si"></xs:enumeration>
                                                        <xs:enumeration value="no"></xs:enumeration>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                            <xs:element name="formato"></xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== darkone0112/xml/xmlSchema/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<videoclub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="videoclub.xsd">
    <cliente id="a1">
        <dni>6066751D</dni>
        <nombre>javier</nombre>
        <apellido1>menendez</apellido1>
        <apellido2>abreu</apellido2>
        <telefono>632199366</telefono>
    </cliente>
    <factura>
        <resguardo>
            <pago>tarjeta</pago>
            <importe>12</importe>
        </resguardo>
        <alquileres fecha="2010-11-12">
            <pelicula idpelicula="a444" valoracion="10">
                <titulo>lotr</titulo>
                <genero>fantasia</genero>
                <duracion>160</duracion>
                <actor>
                    <nombre>aaa</nombre>
                    <apellidos>aaa</apellidos>
                </actor>
                <actor>
                    <nombre>aaa</nombre>
                    <apellidos>aaaa</apellidos>
                </actor>
                <actor>
                    <nombre>aaa</nombre>
                    <apellidos>aaaa</apellidos>
                </actor>
            </pelicula>
        </alquileres>
        <compras>
            <dvd fecha="2010-11-12">
                <extras></extras>
            </dvd>
            <cinta>
                <rebobinada>no</rebobinada>
                <formato>vhs</formato>
            </cinta> 
        </compras>
    </factura>
</videoclub>
